AWeber-Imbi/imbi-api

imbi/endpoints/authentication_tokens.py, imbi/endpoints/base.py, imbi/endpoints/default.py, imbi/endpoints/integrations/gitlab.py, imbi/endpoints/integrations/oauth2.py, imbi/endpoints/metrics.py, imbi/endpoints/openapi.py, imbi/endpoints/status.py, imbi/endpoints/ui/authentication.py, imbi/endpoints/ui/automations/gitlab.py, imbi/endpoints/ui/automations/sonarqube.py, imbi/endpoints/ui/groups.py, imbi/endpoints/ui/index.py, imbi/endpoints/ui/settings.py, imbi/endpoints/ui/user.py, imbi/stats.py, imbi/templates/openapi.yaml, tests/endpoints/test_metrics.py
This change alters the `/metrics` endpoint to return the Prometheus text-based exposition format, including returning a histogram of request duration by endpoint, http method, status, and host.
The `Stats` class needed to change to allow for more complex key structures that can be easily decomposed.
In addition, endpoints with the wrong class attribute name were updated to use the proper attribute name for stats collection.
Testing of the format was performed against the latest Prometheus and included querying to ensure the behaviors matched the desired end result.
=> Move /metrics to be a Prometheus Exporter

imbi/common.py, imbi/endpoints/project_facts.py, imbi/mappings.py, imbi/models.py, imbi/opensearch.py, setup.cfg, tests/base.py, tests/endpoints/test_project_facts.py
We noticed that we were getting questionably correct values in some of our timestamp facts today.  This PR validates the incoming request body to `POST /projects/{id}/facts` against the actual configured fact types in addition to the Open API specification.  I was in the middle of some unrelated cleanup (using sprockets.http.testing and some setup.cfg stuff) so that is in here too.  Sorry for the slightly muddled PR.
=> Sanitize facts in project fact updates

imbi/endpoints/project_facts.py, imbi/endpoints/projects.py, tests/endpoints/test_project_facts.py
When fetching project data at /projects/<project_id>, boolean
facts for the project were always returning a score of 0. The
boolean fact type was just missing and the default 0 was selected.
=> Fix fact score for booleans

docker-compose.yml, docs/configuring-sentry.md, imbi/automations/base.py, imbi/automations/gitlab.py, imbi/automations/sentry.py, imbi/clients/sentry.py, imbi/endpoints/__init__.py, imbi/endpoints/base.py, imbi/endpoints/integrations/gitlab.py, imbi/endpoints/namespaces.py, imbi/endpoints/project_secrets.py, imbi/endpoints/ui/automations/__init__.py, imbi/endpoints/ui/automations/sentry.py, imbi/endpoints/ui/settings.py, imbi/models.py, imbi/server.py, imbi/templates/openapi.yaml, tests/test_server.py
This PR adds an automation that creates and associates a sentry project for an imbi project.  A separate PR to `imbi-ui` will make use of this functionality to enable the automation when creating a new project in imbi.  You can test this locally by creating an API token in sentry.io and following the instructions in _docs/configuring-sentry.md_
=> Add sentry project creation

docker-compose.yml, imbi/endpoints/__init__.py, imbi/endpoints/base.py, imbi/endpoints/project_notes.py, imbi/templates/openapi.yaml
This PR adds CRUD support for project notes without pagination or filtering.  The embedded OpenAPI specification was updated to reflect https://github.com/AWeber-Imbi/imbi-openapi/pull/9 .
=> Add project notes

imbi/app.py, imbi/cors.py, imbi/endpoints/base.py, imbi/server.py, tests/test_cors.py
This PR adds CORS support to the basic request handler to address https://github.com/AWeber-Imbi/imbi/issues/65.  There are a few tunables in the application class that are exposed in the configuration file, but the default behavior should allow [JS fetch](https://fetch.spec.whatwg.org/) to make requests to the various API endpoints.  We can further tune the endpoints to disallow JS access or hide functionality on an endpoint-by-endpoint basis should we find a need to do so.
My goal of this PR is to allow the following to be executed from the JS console in Chrome:
```javascript
window.fetch("http://localhost:8000/projects", {headers: {"Private-Token":"0183a...af6a7c8"}}).then((data)=>{console.log(data)})
```
The inclusion of the `Private-Token` header requires a CORS pre-flight check that …
=> Add CORS support

imbi/static/css/backend.css, imbi/templates/index.html
Some of these styles were inadvertently being applied to the page after tailwind and components loaded. This tightens the scope to a specific element ID to prevent this.
=> Tighten up CSS on initialization page

imbi/endpoints/activity_feed.py, imbi/endpoints/operations_log.py, imbi/endpoints/project_activity_feed.py, imbi/templates/openapi.yaml, tests/endpoints/test_operations_log.py
This PR adds a "type" property to the activity feed, project feed, and operations log entries.  This will be used to distinguish between operations log and project change feed entries when we combine the feeds together for https://github.com/AWeber-Imbi/imbi-ui/issues/30 and https://github.com/AWeber-Imbi/imbi-ui/issues/31.  https://github.com/AWeber-Imbi/imbi-ui/pull/38 is related in that it will protect the client against adding entry types that are not supported by the FE.
Note that this includes the OpenAPI updates from https://github.com/AWeber-Imbi/imbi-openapi/pull/12 inline.
=> Add feed entry type

tests/base.py, tests/endpoints/test_authentication_tokens.py, tests/endpoints/test_cookie_cutters.py, tests/endpoints/test_environments.py, tests/endpoints/test_fact_type_enums.py, tests/endpoints/test_fact_type_ranges.py, tests/endpoints/test_fact_types.py, tests/endpoints/test_groups.py, tests/endpoints/test_metrics.py, tests/endpoints/test_namespaces.py, tests/endpoints/test_operations_log.py, tests/endpoints/test_permissions.py, tests/endpoints/test_project_endpoints.py, tests/endpoints/test_project_facts.py, tests/endpoints/test_project_link_types.py, tests/endpoints/test_project_types.py, tests/endpoints/test_status.py
This PR moves a lot of redundancy into the `self.fetch()` method on our `TestCase`.
- used `self.headers` by default instead of requiring everyone to remember to pass it
- replaced the pattern of `body=json.dumps(...).encode('utf-8')` with `json_body=...` - _there was at least one place where we were missing the `encode()` part_
- removed the need to pass `allow_nonstandard_methods=True` when checking for "method not allowed"
I kept this as a free-standing PR to keep things cleaner.
=> Simplify tests

imbi/common.py, imbi/endpoints/__init__.py, imbi/endpoints/activity_feed.py, imbi/endpoints/base.py, imbi/endpoints/operations_log.py, imbi/endpoints/project_activity_feed.py, imbi/templates/openapi.yaml, tests/endpoints/test_activity_feed.py, tests/endpoints/test_project_activity_feed.py
This PR adds the ops-log entries into both the dashboard activity feed and the project specific activity feed.  I changed the pagination to use token-based pagination instead of limit and offset since we are combining multiple feeds now.  Most of the implementation is in a new `PaginationMixin` in `endpoints.base`.  The commits seem a little backwards because they did not follow the actual implementation path.  I implemented the functionality inline in each handler before pulling it up into a base class and creating the usage contract after the fact.  Once you grok what is going on in the first commit (368c59c6d0144a9bbb1e4d23924c3debf9f09c08), move on to the other implementation commits (1693c11a2409e1f469dfdf2f5f65ed857dd6bb1e and 1693c11a2409e1f469dfdf2f5f65ed857dd6bb1e) and things …
=> Ops log in activity feed

imbi/user.py
This fixes the raised error to match our existing pattern, and logs the error so we actually know what went wrong.
=> Log & raise DatabaseError on user postgres error

docker-compose.yml, imbi/user.py
We need to handle the case where there is a conflict on email_address, not just username, as Google users may have the same email as their LDAP counterparts, and we wish to update that user. Since we can't do two separate ON CONFLICT sections, we moved the logic into a stored proc.
=> Use new upsert_user postgres function

imbi/automations/base.py, imbi/automations/gitlab.py, imbi/automations/sonarqube.py, imbi/clients/gitlab.py, imbi/clients/opensearch.py, imbi/endpoints/integrations/google.py, imbi/endpoints/metrics.py, imbi/errors.py, imbi/ldap.py, imbi/models.py, imbi/oauth2.py, imbi/opensearch/operations_log.py, imbi/opensearch/project.py, imbi/stats.py, imbi/user.py, tests/base.py, tests/endpoints/test_project_facts.py
- Makes opinionated change to reduce the complexity of the user object attributes, so that groups and integrations are just lists of strings. This matches the redis session.
- Makes the user refresh follow our existing patterns when with Google
- Refactor of typehints with `typing.List` and `typing.Dict` to just use `list` and `dict`
=> Fix user dict mismatch with Redis session

imbi/endpoints/integrations/google.py
To ensure compatibility between LDAP users whose usernames match the local part of Google users.
=> Use local part of Google email as username

imbi/models.py, imbi/opensearch/operations_log.py
Currently, if you are on the ops log page and you click on one of the table rows to view the ops log slideout, the "recorded by" will be empty, since it's using the display name of the ops log, and the ops log data is cached from the opensearch response.
=> Add display_name to ops log index

imbi/user.py
Because the as_dict() was setting 'connected_integrations' to 'integrations' in the redis session, when extracting the session the names did not match and so the integrations would appear empty when calling as_dict() on the user object.
=> Ensure user integrations name matches redis name

bootstrap, imbi/server.py, imbi/templates/base.html
This adds an enabled flag to each of the login types in settings: local, ldap, and google. It also passes these forward to the frontend, using the data attributes, so it can dynamically display the valid login methods.
=> Add login methods enabled flag to settings

docker-compose.yml, imbi/endpoints/__init__.py, imbi/endpoints/base.py, imbi/endpoints/integration_identifiers.py, imbi/endpoints/integrations/__init__.py, imbi/endpoints/integrations/_apps.py, imbi/endpoints/project_activity_feed.py, imbi/models.py, imbi/opensearch/project.py, imbi/templates/openapi.yaml, scaffolding/postgres/dml.sql
This PR adds the project identifier related endpoints as described by https://github.com/AWeber-Imbi/imbi-openapi/pull/19.
* `/projects/{id}/integrations` returns the integration identifiers for a project and adds a new one via `POST`
* `/projects/{id}/integrations/{name}` exposes fetch, update, and delete of specific identifiers
* `/integrations` returns the available integrations and adds a new one via `POST`
* `/integrations/{name}` exposes fetch, update, and delete of specific integrations
* the old `/integrations` endpoints are no longer available -- _these were for maintaining OAuth 2 details associated with GitLab and SonarQube_
The updates that were committed as https://github.com/AWeber-Imbi/imbi-openapi/pull/19 are present in the various commits as well. The plan is to merge the …
=> Add project identifiers endpoints

imbi/endpoints/integration_identifiers.py
Without this it was returning all of the external IDs 🤦
=> Add missing WHERE clause to get-ext-id query

imbi/endpoints/integrations/gitlab.py, imbi/endpoints/integrations/google.py, imbi/oauth2.py
This pulls the unique SQL out of the google module and consolidates it into one SQL_UPSERT_TOKEN in the oauth2 module, that can now be used by both Gitlab and Google.
This also adds an optional ID token, and makes refresh tokens optional, as they are in the OAuth 2.0 spec.
=> Consolidate OAuth 2.0 logic

imbi/oauth2.py
Somehow this made it the whole way into a tag before I caught it in my pre-flight check.
=> Fix SQL syntax error in imbi.oauth2

imbi/endpoints/integration_identifiers.py
One of our background processes wasn't updating Imbi correctly. It uses the `/opensearch/projects` endpoint to retrieve a project by a surrogate ID and was failing to match after the project was modified. I narrowed it down to the surrogate identifier endpoints not reindexing the project.  This PR fixes that.
=> Reindex project on surrogate ID changes

.pre-commit-config.yaml, Makefile, ci/test.sh, imbi/__init__.py, imbi/automations/__init__.py, imbi/automations/gitlab.py, imbi/clients/gitlab.py, imbi/endpoints/integrations/gitlab.py, imbi/endpoints/integrations/models.py, imbi/endpoints/integrations/oauth2.py, imbi/endpoints/projects.py, setup.cfg, tests/automations/test_context.py, tests/endpoints/test_operations_log.py, tests/test_cors.py
This PR builds on top of #72 by adding the `imbi.automations.gitlab.create_project` function that can be used as an automation callable. It does required that you have an OAuth 2 application defined in GitLab that is used to authorize Imbi to act as a specific GitLab user. You will need the OAuth 2 Client ID and Client Secret for that application to continue (details below).
Once you have the GitLab connection configured and a user connected, creating a new project of a project type that has automations enabled will add toggles for each available automation to the display.
After creating the Imbi project, the project creation endpoint will run the selected automations (8400ff4b2a686fb2df29b71fe2bffe00d3790888). If none of the automations fail, then the endpoint responds with a 👍 to the …
=> Add automation to create a gitlab project

.pre-commit-config.yaml, imbi/automations/__init__.py, imbi/automations/sonarqube.py, imbi/clients/sonarqube.py, imbi/endpoints/base.py, imbi/endpoints/integrations/integrations.py, imbi/endpoints/projects.py, imbi/server.py, imbi/templates/openapi.yaml
This PR adds an automation for creating SonarQube projects. It creates the project and sets up the ALM connection for GitLab if enabled.
> There is one wrinkle currently ... the GitLab integration MUST be named `gitlab` for it to work properly. I could work around this by looking for the `imbi.automations.gitlab.create_project` key in the automation context and using the integration name from there. That didn't feel quite right to me .... _yet_
I did add the obscured `api_secret` to the `/integrations` read endpoints as well. There will be an OpenAPI PR for that shortly. This makes it much easier to determine if you have the wrong key set versus not having one set at all.
<details>
<summary>Configure SonarQube integration</summary>
You will need to set the …
=> Implement SonarQube project creation automation

compose.yml, imbi/automations/models.py, imbi/automations/pagerduty.py, imbi/clients/pagerduty.py, imbi/endpoints/integrations/automations.py, imbi/endpoints/integrations/oauth2.py, imbi/endpoints/namespaces.py, imbi/models.py, imbi/server.py, imbi/templates/openapi.yaml, tests/base.py, tests/test_pagerduty_client.py
This PR adds an automation that creates a PagerDuty Service linked to the new Imbi project. The implementation uses a [API  Key](https://developer.pagerduty.com/docs/f59fdbd94ceab-o-auth-functionality#oauth-or-pagerduty-api-key) that you create in your PagerDuty account to create services. The automation creates a new PD service if the user enables the "Create PagerDuty Service" automation *and* the selected namespace has a `pagerduty_policy` property set. The policy identifies the Escalation Policy that the service is associated with. The resulting service identifier is stored as a "pagerduty" external identifier for the project. If the `/automations/pagerduty/project_link_type_id` configuration value is set, then the automation will add a link to the dashboard using the configured link …
=> Create PagerDuty service automation

imbi/endpoints/projects.py
The ordering of the project urls in the UI reflects the order of the `environments` property in the `/projects/{id}` response. This PR sorts the `environments` list so that it is consistent across projects. This will address the issue with the current UI but does not really fix the problem there.
See https://github.com/AWeber-Imbi/imbi-ui/issues/74 for the genesis of this change.
=> Sort the Project.environments property

imbi/endpoints/ui/authentication.py
We missed this when we moved it into settings.
=> Fix GoogleLoginRequestHandler.integration_name

imbi/endpoints/project_ssm_configuration.py
It was instead 500ing due to iterating through the environments, which is None when they don't exist. We can just exit early since zero environments means zero params.
=> Return no params for project without environments

imbi/endpoints/project_ssm_configuration.py, imbi/errors.py
This makes the errors use a proper json problemdetails while still passing the reason to the frontend (displayed in "title")
=> Use our custom errors when fetching SSM

imbi/endpoints/components.py, imbi/templates/openapi.yaml
We want to show the number of projects using a component along with the number of versions that exist in the DB in the Components admin view. This PR adds two new properties to the `GET /components` response for this. The API is used in https://github.com/AWeber-Imbi/imbi-ui/pull/79 and described in https://github.com/AWeber-Imbi/imbi-openapi/pull/27.
=> Add admin props to GET /components

imbi/endpoints/reports/__init__.py, imbi/endpoints/reports/component_usage.py, imbi/endpoints/reports/namespace_kpis.py, imbi/endpoints/reports/namespace_shs_history.py, imbi/endpoints/reports/system_shs_history.py, imbi/templates/openapi.yaml
This PR adds a simple component usage report that contains the known components. Each component is an array element with basic information, the number of projects using the component, and the number of known versions. See https://github.com/AWeber-Imbi/imbi-openapi/pull/29 for the PR that generated the OpenAPI spec.
=> Add component-usage report

compose.yml
This PR simply bumps the imbi-postgres version [to 0.22.2](https://hub.docker.com/layers/aweber/imbi-postgres/0.22.2/images/sha256-bc926a330f9398ad06bee45f9e65e831ea969dc48682d861419539ef786b9c9f)
=> Bump imbi-postgres to 0.22.2

imbi/endpoints/ssm/handlers.py
This reverts commit 3df884b8447cc5069b035d02ddf2b7ad83cf4333. This is used when refreshing oauth2 tokens.
=> Revert "Remove unnecessary HTTPClientMixin base class"

imbi/endpoints/project_sbom/handlers.py, imbi/models.py
This PR reindexes the project in the OpenSearch index after ingesting a SBoM.  I noticed that the indexed content was using the `name` instead of the `package_url` so I fixed that as well... _this was a direct result of not reindexing since I didn't notice that it was broken in dev_.
The last commit (b2efa309) adds a new field to the index named `component_versions` that is a list of `{package_url}@{version}` strings for components. This is a temporary workaround for shortcoming in our FE query builder. The version of kbn-es-query that we are using does not support nested query syntax. The workaround is to flatten the values in the index for the time being.
=> Reindex the project after ingesting a SBoM

imbi/endpoints/project_dependencies.py, imbi/templates/openapi.yaml
This adds the potential query string param "includes" where the request can specify that it wants extra information about the project dependencies. This will be used by the frontend to populate a dependency table.
Corresponding openapi PR: https://github.com/AWeber-Imbi/imbi-openapi/pull/35
=> Add optional project info in dependency endpoint

imbi/automations/__init__.py, imbi/automations/models.py, imbi/endpoints/base.py, imbi/endpoints/project_dependencies.py, imbi/endpoints/projects.py, imbi/models.py, imbi/openapi.py, imbi/templates/openapi.yaml, setup.cfg
This adds the plumbing for create and remove project dependency automations, on the POST and DELETE endpoints. Some of the generic automations code got moved out of project creation and put into the `automations` package, to be re-used by the new dependency automations.
=> Run automations on project dependency add/delete

compose.yml
This PR pins versions in the docker compose environment. For some reason the latest version of opensearch does not work correctly on my machine 😞
=> Pin versions

imbi/automations/pagerduty.py, imbi/clients/pagerduty.py
This adds the two automation callables to associate and disassociate Pagerduty service dependencies, to be executed upon adding and removing project dependencies respectively. Both will bail early if either the dependent or dependency project don't have Pagerduty set up. Then they check if the service dependency already exists in Pagerduty itself, and performs the corrective action if needed.
=> Add Pagerduty dependency automations

bootstrap, example.yaml, imbi/app.py, imbi/endpoints/components/handlers.py, imbi/endpoints/components/models.py, imbi/endpoints/components/scoring.py, imbi/server.py
After some internal debate, I decided to switch from an enumerated fact type to a range fact type for component scores. The primary driver was that using an enumerated value meant that the user was required to manually create an enumerated fact type _with enumeration values that matched what was in the code_. This just felt funky...
This PR switches to a range fact type with three ranges (0-20), (20.01-80), and (80.01-100). My goal was to maximize the central range so that we can do something more interesting in the future. I also added project fact type creation during application initialization to remove the manual configuration requirement altogether.
=> Switch to numeric component score

imbi/automations/pagerduty.py
Was accidentally passing the Imbi project ID instead of the Pagerduty service ID.
=> Use correct ID for Pagerduty service requests

imbi/app.py, imbi/endpoints/components/handlers.py, imbi/endpoints/components/models.py, imbi/endpoints/components/scoring.py, imbi/endpoints/reports/__init__.py, imbi/endpoints/reports/outdated_projects.py, imbi/server.py, imbi/templates/openapi.yaml
This PR adds a new report that lists projects that contain outdated components. I moved the per-version component status into the database (see https://github.com/AWeber-Imbi/imbi-schema/pull/26) to make this much easier. This is done analogous to how project scores are maintained. The implementation is in 9e9376c5ed07c305de482289c60e44b3b9761880.
The report contains rows like the following for _every project that contains an outdated, deprecated, or forbidden component_. This corresponds with projects that are scored in the "needs work" and "unacceptable" categories.
```json
{
"project_id": 1,
"project_namespace": "Some Namespace",
"project_name": "Some Project",
"component_score": 80,
"unscored": 61,
"up_to_date": 3,
"outdated": 0,
"deprecated": 1,
"forbidden": 0
}
```
Note that the …
=> Add Outdated Projects report

imbi/endpoints/base.py, imbi/endpoints/project_score_details.py
The `ProjectScoreDetailHandler` was generating SQL with empty `IN()` clauses if the project did not have enum or range facts.  I added some `if` statements to guard against the empty sets. I also implemented a postgres exception handler that logs the exception stack.
=> Handle project score details requests for projects w/o range/enum facts

compose.yml, imbi/endpoints/operations_log.py, imbi/models.py, imbi/templates/openapi.yaml, tests/base.py, tests/endpoints/test_activity_feed.py, tests/endpoints/test_operations_log.py, tests/endpoints/test_project_activity_feed.py
This is the user supplied value for when the event occurred at as opposed to when the event was created at.
I also removed the ability to set or change the "recorded_by" property since that should always come from the authorization token. The same for the "recorded_at" property.
This includes the rendered version of https://github.com/AWeber-Imbi/imbi-openapi/pull/42
This also requires that https://github.com/AWeber-Imbi/imbi-schema/pull/28 is merged and released BEFORE the tests will pass.
=> Add operations log occurred at property

compose.yml, imbi/endpoints/base.py, imbi/endpoints/operations_log.py, imbi/models.py, imbi/opensearch/operations_log.py, imbi/templates/openapi.yaml, scaffolding/postgres/y01-migration.sql, scaffolding/postgres/z02-imbi-db.sh
The Operations Log `recorded_by` field is the **username** that recorded the operations log entry. It uses the authenticated user so that we do not lose track of who recorded an entry. The field is used in a join against `v1.users` to get the display name and email address of the user when returning an ops log record across the API.
This PR adds the `performed_by` optional field that is used instead of `recorded_by` when determining the display name and email address. The database schema (https://github.com/AWeber-Imbi/imbi-schema/pull/29) uses a foreign key relationship to ensure that the value refers to a valid user when it is set and nullifies the column when the user is deleted.
I found a few bugs when implementing this feature so I squashed them as well.
* …
=> Add override to Operations Log recorded_by and related fields

imbi/endpoints/integrations/notifications/processing.py, imbi/opensearch/operations_log.py, imbi/opensearch/project.py
This PR reindexes a project after processing a notification for it. I missed this during implementation of notification processing. I added a new method to the project and operations log indexing helpers to index a document by ID so that I did not have to look up the model using the "other" model. My plan is to introduce POST methods to reindex specific documents by ID since it keeps coming up. That will be in a future PR.
=> Reindex projects during notification processing

imbi/endpoints/operations_log.py, imbi/endpoints/projects.py, imbi/opensearch/__init__.py, imbi/opensearch/operations_log.py, imbi/opensearch/project.py, imbi/templates/openapi.yaml
This PR removes a lot of duplication in the ops log and project opensearch helpers. I also added the ability to limit reindexing endpoints to one or more objects by including one or more `id=N` query parameters.
This includes the output of https://github.com/AWeber-Imbi/imbi-openapi/pull/45
=> Refactor OpenSearch helpers

CHANGELOG.md, imbi/endpoints/integrations/notifications/processing.py
We had a few instances of more than one Imbi project connected to a single GitLab project. The notification processing was failing with a glorious 500 because the implementation was assuming a one-to-one relationship. It was easy enough to iterate over multiple projects and apply updates.
=> Handle notifications that match multiple projects

imbi/openapi.py
This should resolve https://github.com/AWeber-Imbi/imbi/issues/112
The [default scheme validator](https://github.com/python-validators/validators/blob/master/src/validators/url.py#L42-L65) has a specific set of protocols it allows.
=> Allow arbitrary schemes for project URL validation

imbi/automations/github.py, imbi/clients/github.py, imbi/endpoints/integrations/github.py, imbi/endpoints/project_types.py, imbi/models.py, imbi/templates/openapi.yaml, tests/endpoints/test_project_types.py
Corresponding PRs: 
- ddl: https://github.com/AWeber-Imbi/imbi-schema/pull/31
- openapi: https://github.com/AWeber-Imbi/imbi-openapi/pull/46
This adds the `github_org` to the models and API responses. And crucially adds support for using it in repository creation, overriding the project type slug if present.
=> Add `github_org` override

imbi/endpoints/integrations/notifications/processing.py
This starts the implementation of validating webhook secrets, starting with the `github` integration. Others can be added here. If there is no verification token, we skip validation, like we are currently. If it exists, it must validate against one of the integrations we implement it for (again, for now, only `github`).
=> Add webhook validation
