- Makefile
- ci/config.yaml
- ci/test.sh
- docker-compose.yml
- docker-config.yaml
- example.yaml
- imbi/app.py
- imbi/openapi.py
- imbi/opensearch.py
- scaffolding/ldap/97-limit-memory.ldif
- setup.cfg
- tests/base.py
This PR is a handful of test improvements.  I saw about a 10x speedup by caching the rendered OpenAPI spec since it was being loaded effectively with every test method.  I also reduced the memory used by the OpenLDAP container and shut down the OpenSearch client since it was leaking sockets on every test iteration previously.
> Test improvements

- imbi/endpoints/ui/settings.py
The `/ui/settings` endpoint was no longer returning the GitLab application settings that enable connecting a user to GitLab.  This PR adds the GitLab information back into the response.
> Fix gitlab information in /ui/settings

- imbi/templates/openapi.yaml
Incorporates the update from https://github.com/AWeber-Imbi/imbi-openapi/pull/16.
Closes #36 
Closes https://github.com/AWeber-Imbi/imbi-openapi/issues/13
> Fix GET /projects response docs

- imbi/templates/openapi.yaml
> Updated openapi.yaml for null JSON patch values

- imbi/user.py
Ensures user type is `google` with a Google user
> Set google user type

- imbi/app.py
- imbi/endpoints/integrations/google.py
- imbi/endpoints/ui/authentication.py
- make google integration name dynamic per environment
- fix bug where Sentry was grabbing wrong env variable
> Use dynamic Google integration name

- imbi/endpoints/metrics.py
Closes https://github.com/AWeber-Imbi/imbi/issues/92
> Prefix imbi prometheus metrics with 'imbi_'

- imbi/endpoints/integrations/google.py
- imbi/endpoints/ui/authentication.py
- imbi/session.py
- imbi/user.py
Yapf wanted to make a few changes.  I added pre-commit to the Makefile a while back to prevent this from happening.  Maybe I never ran yapf over the older code.  Anyway, this makes yapf 0.31.0 happy.
> Run yapf over codebase

- .github/workflows/service-testing.yaml
- CONTRIBUTING.md
- Makefile
- bootstrap
- ci/test.sh
- compose.yml
- docker-compose.yml
Updates to the new, standard compose.yml file and `docker compose` command. This also replaces the redis image to an updated alpine version.
> Update compose dev environment

- imbi/endpoints/integrations/notifications/processing.py
There is nothing that prohibits having multiple Imbi projects with the same surrogate identifier. Notification processing was failing in that case. This PR fixes that by updating facts in any project with the surrogate identifier.
> Fix notifications for projects with same ext id

- imbi/automations/__init__.py
- imbi/automations/gitlab.py
- imbi/automations/sentry.py
- imbi/clients/gitlab.py
- imbi/clients/sentry.py
- imbi/endpoints/integrations/gitlab.py
- imbi/endpoints/integrations/models.py
- imbi/errors.py
- imbi/models.py
- imbi/server.py
- tests/automations/test_context.py
- tests/test_server.py
This PR adds the `imbi.automations.sentry.create_project` automation which creates a project in Sentry during the creation of an Imbi project. This builds on the foundation created in #73 so the code here is a lot simpler.
I reworked `imbi.clients.gitlab` and `imbi.clients.sentry` to expose an async `create_client` function instead of a public client class. This let me push the database operations related to tokens and configuration into create function instead of relying on users to do the various async ops before constructing a client and then checking the configuration in the client.
I also changed the automation notes to be a data class instead of a tuple. I'm planning on returning these from project creation to the UI at some point in the future after some discussion with co-workers. …
> Create sentry project

- imbi/automations/gitlab.py
- imbi/automations/sentry.py
- imbi/endpoints/integrations/models.py
- imbi/endpoints/integrations/oauth2.py
- imbi/oauth2.py
This PR contains a few adjustments that were needed when I integration tested against _both_ GitLab and Sentry with various things misconfigured. I also should not have encrypted the client secret in b1282e10842edd12929de355e18a1be94711e64a ... it blew up in my face when I ran with existing information in the database 🤕
I'll come back with another PR to encrypt the things that need to be encrypted and remove duplicated configuration values & keys in the future.
> Adjustments from really testing

- imbi/automations/pagerduty.py
- imbi/clients/pagerduty.py
- tests/test_pagerduty_client.py
I created the automation in #78. We will also need [an inbound event integration](https://developer.pagerduty.com/api-reference/43e0864d370fb-create-a-new-integration) that receives events for the new service. This is the _Integration Key_ that you need to connect a [Grafana contact point and a PagerDuty service](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/manage-contact-points/integrations/pager-duty/). The value is available as the `pagerduty-integration-key` secret from `/projects/{id}/secrets`.
> Create incoming event integration for PD services

- imbi/clients/aws.py
- imbi/endpoints/project_ssm_configuration.py
- imbi/templates/openapi.yaml
This adds a new endpoint to delete sets of SSM params for a given name (path). Users can submit a list of environments they want to delete that param in.
> Delete SSM params

- imbi/endpoints/__init__.py
- imbi/endpoints/aws_roles.py
- imbi/templates/openapi.yaml
Adds the admin-gated streamlined CRUD endpoints for manipulating AWS roles in the db.
> Add endpoints for AWS Role CRUD

- imbi/endpoints/project_sbom/handlers.py
We were leaving the empty sets in the cache for packages that were not in the database. This caused the `KeyError` logic in `insert_component_version` to fail. I switched to only caching positive entries instead of priming the cache with every package in the SBoM. The result is that the cache faithfully represents what is in the database when we start the ingest.
> Fix component_versions caching during SBoM ingest

- imbi/endpoints/project_dependencies.py
- imbi/models.py
- imbi/opensearch/project.py
Also add the missed index update on dependency delete.
> Add project dependencies to opensearch index

- imbi/endpoints/ui/user.py
This will close https://github.com/AWeber-Imbi/imbi-api/issues/108
> Add categories to available automations response

- imbi/app.py
- imbi/endpoints/components/scoring.py
- imbi/server.py
This avoids a race condition caused when we run more than one process in a container 🤨 
I added a flag to the Application to avoid some log messages if we are running with `--initialize`. We may want to use it to control other things like not setting up the sentry connection for CLI usage.
> Move scoring initialization into --initialize

- imbi/endpoints/operations_log.py
- imbi/templates/openapi.yaml
This contains the build output of https://github.com/AWeber-Imbi/imbi-openapi/pull/40
https://github.com/AWeber-Imbi/imbi/issues/90
> Reject null & empty ops log descriptions

- imbi/templates/openapi.yaml
This is the output from https://github.com/AWeber-Imbi/imbi-openapi/pull/41. It also addresses https://github.com/AWeber-Imbi/imbi/issues/91.
> OpenAPI update for comma-separated ticket slugs

- imbi/endpoints/activity_feed.py
- imbi/endpoints/project_activity_feed.py
I missed these when I added the `performed_by` field in #119
> Fix the user display_name in "feeds"
